USE f1gameinfo;
INSERT INTO PILOTOS (NOMBRE, NOMBRE_EQUIPO, EDAD, VICTORIAS, PODIOS, CARRERAS, DESCRIPCION, ANHO_DEBUT, VALORACION, PRECIO, RUTA_IMAGEN) VALUES
('Lewis Hamilton', 'Ferrari', 40, 105, 202, 366, 'El mejor para muchos, buscando el reto mas grande de su vida, ser campeón con Ferrari.', 2007, 95, 5000, '/uploads/images/hamilton.avif'),
('Max Verstappen', 'Red Bull', 27, 63, 112, 219, 'Vigente campeón, camino de batir todos los records por haber.', 2015, 98, 5800, '/uploads/images/verstappen.avif'),
('Charles Leclerc', 'Ferrari', 27, 8, 43, 157, '"Il Predestinato" se enfrenta a su reto más grande, un heptacampeón como compañero.', 2018, 94, 4900, '/uploads/images/leclerc.avif'),
('George Russell', 'Mercedes', 27, 3, 15, 138, 'Tras la marcha de Hamilton, debe llevar las riendas de Mercedes.', 2019, 92, 4500, '/uploads/images/russell.avif'),
('Lando Norris', 'McLaren', 25, 4, 26, 138, 'A pesar de tener el mejor coche no pudo ganar a Max en 2024. ¿Se vengará en 2025?.', 2019, 92, 4500, '/uploads/images/norris.avif'),
('Carlos Sainz', 'Williams', 30, 4, 27, 216, 'Tras una gran etapa en Ferrari, le tocará sufrir más con un cocne inferior en 2025.', 2015, 92, 4500, '/uploads/images/sainz.avif'),
('Jack Doohan', 'Alpine', 22, 0, 0, 11, 'Desde antes de empezar la temporada ya peligraba su puesto, tiene que sobrevivir esta temporada.', 2025, 76, 1100, '/uploads/images/doohan.avif'),
('Fernando Alonso', 'Aston Martin', 43, 32, 106, 413, 'Gran piloto, entorpecido por malas elecciones de equipos, buscando la 33.', 2001, 96, 5200, '/uploads/images/alonso.avif'),
('Esteban Ocon', 'Haas', 28, 1, 4, 166, 'El que fuese pupilo de Mercedes no encuentra un coche ganador, y esta temporada no será distinto.', 2016, 85, 3200, '/uploads/images/ocon.avif'),
('Pierre Gasly', 'Alpine', 29, 1, 5, 163, 'Tras derrocar a Ocon esta temporada se le plantea un reto a priori, mas sencillo.', 2017, 86, 3500, '/uploads/images/gasly.avif'),
('Lance Stroll', 'Aston Martin', 26, 0, 3, 176, 'El Canadiense que en algún momento deslumbró al mundo, cada temporada se diluye más.', 2017, 81, 2200, '/uploads/images/stroll.avif'),
('Oliver Bearman', 'Haas', 20, 0, 0, 13, 'Pupilo de Ferrari, si Leclerc no gana el mundial con ellos, Oliver quizá lo haga.', 2024, 81, 2200, '/uploads/images/bearman.avif'),
('Oscar Piastri', 'McLaren', 24, 0, 10, 56, 'Considerado un supertalento, pero con un 2024 lleno de irregularidad debe dar el paso adelante ya.', 2023, 89, 4000, '/uploads/images/piastri.avif'),
('Yuki Tsunoda', 'Racing Bulls', 25, 0, 0, 97, 'Su futuro peligra en F1, Red Bull no cuenta con el para el futuro. ¿Seguirá aquí en 2026?.', 2021, 85, 3200, '/uploads/images/tsunoda.avif'),
('Gabriel Bortoleto', 'Kick Sauber', 20, 0, 0, 10, 'El siguiente Senna para algunos, y no es para menos, pero este 2025 tendrá que sufrir.', 2025, 82, 2400, '/uploads/images/bortoleto.avif'),
('Alex Albon', 'Williams', 29, 0, 2, 114, 'Para muchos infravalorado, otros le consideran sobrevalorado y que Sainz le destruirá.', 2019, 85, 3200, '/uploads/images/albon.avif'),
('Kimi Antonelli', 'Mercedes', 18, 0, 0, 10, 'Hacía mucho que un novato no debutaba en un equipo grande, es la señal de un gran futuro.', 2025, 82, 2400, '/uploads/images/antonelli.avif'),
('Nico Hulkenberg', 'Kick Sauber', 37, 0, 0, 237, 'Experienca, experienca y más experiencia, gran piloto, pero el podio no llega.', 2010, 87, 3700, '/uploads/images/hulkenberg.avif'),
('Isack Hadjar', 'Racing Bulls', 20, 0, 0, 10, 'La "niña bonita" de Red Bull, mucho carácter y talento puro, que puede llevar a lo mejor o lo peor.', 2025, 81, 2200, '/uploads/images/hadjar.avif'),
('Liam Lawson', 'Red Bull', 23, 0, 0, 21, 'Odiado por todo México, pero no le importa mucho. Temporada que le consolidará o destruirá.', 2023, 84, 2900, '/uploads/images/lawson.avif');
