USE f1gameinfo;
INSERT INTO CIRCUITOS (NOMBRE, PAIS, DESCRIPCION, ANHO_CONSTRUCCION, PRECIO, RUTA_IMAGEN) VALUES
('Mónaco', 'Mónaco', 'Donde los verdaderos pilotos brillan. Glamour, riqueza y lujuria.', 1929, 5800, '/uploads/images/monaco.avif'),
('Silverstone', 'Reino Unido', 'El circuito más histórico de la Fórmula 1, amado por todos.', 1948, 5500, '/uploads/images/silverstone.avif'),
('Spa-Francorchamps', 'Bélgica', 'Circuito rápido, precioso y enorme. Pero muy peligroso.', 1921, 5200, '/uploads/images/spa.avif'),
('Monza', 'Italia', 'El "Templo de la Velocidad", donde los pilotos pasan más tiempo con el acelerador a tope.', 1922, 5500, '/uploads/images/monza.avif'),
('Suzuka', 'Japón', 'Circuito muy particular, increiblemente rápido, y casa de la famosa "130R".', 1962, 5000, '/uploads/images/suzuka.avif'),
('Interlagos', 'Brasil', 'El juez final de muchos campeonatos de pilotos y equipos.', 1940, 4800, '/uploads/images/interlagos.avif'),
('Montreal', 'Canadá', 'Si un muro tiene nombre propio "El Muro de los Campeones", no es por nada bueno.', 1978, 3200, '/uploads/images/montreal.avif'),
('Albert Park', 'Australia', 'Por regla general el primer Gran Premio de cada año, muy rápido y peligroso.', 1996, 2500, '/uploads/images/melbourne.avif'),
('Montmeló', 'España', 'Circuito amado por ingenieros, pues es perfecto para demostrar qué tan bueno es un coche.', 1991, 3800, '/uploads/images/barcelona.avif'),
('Hungaroring', 'Hungría', 'Circuito muy ratonero, adelantar aquí es una osadia al alcance de pocos.', 1986, 2800, '/uploads/images/hungaroring.avif'),
('Singapur', 'Singapur', 'Circuito urbano, nocturno y cálido, el horror de los pilotos.', 2008, 2200, '/uploads/images/singapur.avif'),
('Abu Dhabi', 'Emiratos Árabes Unidos', 'Circuito nocturno, casa de muchos cierres de temporada, no tiene muchos fanáticos.', 2009, 1500, '/uploads/images/abudhabi.avif'),
('Circuit of the Americas', 'Estados Unidos', 'Mucha curva rápida y cambio de elevación, pero con rectas largas que da espectáculo.', 2012, 2500, '/uploads/images/cota.avif'),
('Zandvoort', 'Países Bajos', 'Casi tan ratonero como Hungría, la locura por Max Verstappen aquí no tiene límites.', 1948, 3100, '/uploads/images/zandvoort.avif'),
('Jeddah', 'Arabia Saudita', 'Circuito urbano, rápido y peligroso, que pese a tener sus detractores, siempre ofrece un gran espectáculo.', 2021, 2500, '/uploads/images/jeddah.avif'),
('Miami', 'Estados Unidos', 'Parte de la ambición de la F1 de expandirse a los EEUU, pero no acaba de cuajar.', 2022, 1200, '/uploads/images/miami.avif'),
('Las Vegas', 'Estados Unidos', 'Circuito muy difícil, que si bien es raro, propicia muchas batallas.', 2023, 95000000, '/uploads/images/vegas.avif'),
('Circuito de Shanghai', 'China', 'Circuito muy peculiar, que carece de muchos fanáticos dentro del mundillo, pero que siempr se mantiene.', 2004, 1100, '/uploads/images/shanghai.avif'),
('Bakú', 'Azerbaiyán', 'Tiene la curva más difícil de todo el calendario, en la que de milagro cabe un coche, e irónicamente la recta más larga.', 2016, 2500, '/uploads/images/baku.avif'),
('Sakhir', 'Baréin', 'Circuito que por sus carácterísticas suele provocar que buenos coches no rinda, y malos coches sorprendan por arriba.', 2014, 3500, '/uploads/images/sakhir.avif'),
('Red Bull Ring', 'Austria', 'El circuito más corto con diferencia, que provoca sesiones de clasificación muy intensas.', 2005, 4100, '/uploads/images/spielberg.avif'),
('Autódromo Hermanos Rodríguez', 'México', 'Existen pocos circuitos mas planos, caracterizado por destrozar los neumáticos de los pilotos.', 2008, 3200, '/uploads/images/mexico.avif'),
('Lusail', 'Qatar', 'Cuidado con los pianos aquí, que son capaces de rajar el neumático.', 1927, 2600, '/uploads/images/qatar.avif'),
('Imola', 'Italia', 'Circuito de la vieja escuela donde los haya, es muy difícil no amarlo.', 1953, 4600, '/uploads/images/imola.avif');
