CREATE DATABASE f1gameinfo; 
CREATE TABLE PILOTOS ( 
	ID BIGINT AUTO_INCREMENT NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	NOMBRE_EQUIPO VARCHAR(50) NOT NULL, 
	EDAD INTEGER NOT NULL, 
	VICTORIAS INTEGER NOT NULL, 
	PODIOS INTEGER NOT NULL, 
	CARRERAS INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(500) NOT NULL, 
	ANHO_DEBUT INTEGER NOT NULL, 
	VALORACION INTEGER NOT NULL, 
	PRECIO BIGINT NOT NULL,
    RUTA_IMAGEN VARCHAR(255),
	PRIMARY KEY(ID) 
); 
CREATE TABLE CIRCUITOS ( 
	ID BIGINT AUTO_INCREMENT NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	PAIS VARCHAR(50) NOT NULL, 
	DESCRIPCION VARCHAR(500) NOT NULL, 
	ANHO_CONSTRUCCION INTEGER NOT NULL, 
	PRECIO BIGINT NOT NULL,
	RUTA_IMAGEN VARCHAR(255),
	PRIMARY KEY(ID) 
); 
CREATE TABLE USUARIOS ( 
	ID BIGINT AUTO_INCREMENT NOT NULL, 
	USERNAME VARCHAR(50) UNIQUE NOT NULL, 
	PASSWORD VARCHAR(150) NOT NULL,
    MONEDAS INTEGER NOT NULL,
	PRIMARY KEY(ID) 
); 
CREATE TABLE USUARIO_PILOTOS( 
	ID_PILOTO BIGINT NOT NULL, 
	ID_USUARIO BIGINT NOT NULL, 
	FOREIGN KEY(ID_PILOTO) REFERENCES PILOTOS(ID), 
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID) 
); 
CREATE TABLE USUARIO_CIRCUITOS( 
	ID_CIRCUITO BIGINT NOT NULL, 
	ID_USUARIO BIGINT NOT NULL, 
	FOREIGN KEY(ID_CIRCUITO) REFERENCES CIRCUITOS(ID), 
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID) 
);